import { Router } from "express";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import restaurantRoutes from "./restaurant.routes";
import orderRoutes from "./order.routes";
import inventoryRoutes from "./inventory.routes";
import insightsRoutes from "./insights.routes";
import expenseRoutes from "./expense.routes";
import employeeRoutes from "./employee.routes";
import payrollRoutes from "./payroll.routes";
import dashboardRoutes from "./dashboard.routes";
import notificationRoutes from "./notification.routes";
import menuRoutes from "./menu.routes";
import onlineOrderRoutes from "./onlineOrder.routes";
import publicRoutes from "./public.routes";
import inventoryRequestRoutes from "./inventoryRequest.routes";
const router = Router();
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/restaurants", restaurantRoutes);
router.use("/orders", orderRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/insights", insightsRoutes);
router.use("/expenses", expenseRoutes);
router.use("/employees", employeeRoutes);
router.use("/payroll", payrollRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/notifications", notificationRoutes);
router.use("/menu", menuRoutes);
router.use("/online-orders", onlineOrderRoutes);
router.use("/public", publicRoutes);
router.use("/inventory-requests", inventoryRequestRoutes);

export default router;
